server:
  port: 9001
spring:
  rabbitmq:
    host: 192.168.10.168
    port: 5672
    username: qipai
    password: qipai1979
  cloud:
    stream:
      bindings:
        testHeaders:
          destination: testHeaders
        testDirect:
          destination: testDirect
        testTopic:
          destination: testTopic
      rabbit:
        bindings:
          testHeaders:
            producer:
              exchangeType: headers
          testDirect:
            producer:
              exchangeType: direct
              routingKeyExpression: headers.routeTo