server:
  port: 9000
spring:
  rabbitmq:
    host: 192.168.10.168
    port: 5672
    username: qipai
    password: qipai1979
  cloud:
    stream:
      bindings:
        testHeaders:
          destination: testHeaders
          group: test
        testDirect:
          destination: testDirect
          group: test
        testTopic:
          destination: testTopic
          group: test

      rabbit:
        bindings:
          testHeaders:
            consumer:
              exchangeType: headers
              queueBindingArguments:
                key1: seven
          testDirect:
            consumer:
              exchangeType: direct
              bindingRoutingKey: key1