server:
  port: 9002
spring:
  rabbitmq:
    host: 192.168.10.176
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        testPartition:
          destination: testPartition
          group: test
          consumer:
            partitioned: true
        testPartitionExtractor:
          destination: testPartitionExtractor
          group: test
          consumer:
            partitioned: true
      instanceCount: 2
      instanceIndex: 1